iaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
tttttttttttttttttttttttttttttttt
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccc
dddddddddddddddddddddddddddddddd
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
ffffffffffffffffffffffffffffffff

